# Nixpacks configuration for Coolify deployment

# Node.js provider (auto-detected)  
providers = ["node"]

# Install pnpm directly without corepack signature issues
[phases.setup]
cmds = [
  "npm install -g pnpm@8.15.6"
]

# Use pnpm for all operations
[phases.install]
cmd = "pnpm install --frozen-lockfile"

[phases.build]
cmd = "pnpm build"

[start]
cmd = "pnpm start"

# Environment variables
[variables]
NODE_VERSION = "18"